// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package model

import ()

type Session struct {
	ID          int32
	UserID      int32
	AccessToken string
}

type User struct {
	ID           int32
	Name         string
	PasswordHash string
}
