// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package model

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, password_hash) VALUES ($1, $2)
`

type CreateUserParams struct {
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.PasswordHash)
	return err
}

const getUserByName = `-- name: GetUserByName :one
SELECT name, password_hash FROM users WHERE name = $1 LIMIT 1
`

type GetUserByNameRow struct {
	Name         string
	PasswordHash string
}

func (q *Queries) GetUserByName(ctx context.Context, name string) (GetUserByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i GetUserByNameRow
	err := row.Scan(&i.Name, &i.PasswordHash)
	return i, err
}
